#!/usr/bin/env bash
# Install the dev-flow into a repo.
#
#   ./bootstrap.sh [--dry-run] [--update-hooks] /path/to/repo [voice-agent|greenfield|general] [vercel|docker-vps]
#
# Idempotent: safe to re-run. Never overwrites an existing file — it reports and
# skips, so a repo that has diverged from this scaffold keeps its divergence.
# Two files are changed in place. .claude/settings.json: scripts/settings_merge.py
# merges the shipped settings into it entry by entry, after a backup, and refuses
# a file it cannot parse (that script's header has the rules). .gitignore: the
# Playwright Test output directories, dev-flow's run state (.dev-flow-run/) and
# Python's bytecode (__pycache__/) are appended when absent, never rewritten.
#
# --dry-run prints every write and merge it would make, and writes nothing.
# --update-hooks gives the project's existing entries for dev-flow's hook scripts
# the shipped matcher and timeout (DECISIONS.md B4). Without it an existing entry
# is kept as it is, with a warning when it differs, so a project wired before a
# shipped matcher or timeout changed keeps the old one until you ask. It changes
# nothing else: not the hook scripts (delete one to take the new copy), and not
# hooks dev-flow does not ship.

set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DRY_RUN=0
UPDATE_HOOKS=()
ARGS=()
for a in "$@"; do
  case "$a" in
    --dry-run)      DRY_RUN=1 ;;
    --update-hooks) UPDATE_HOOKS=(--update-hooks) ;;
    *)              ARGS+=("$a") ;;
  esac
done
set -- ${ARGS[@]+"${ARGS[@]}"}
# Core installs the spec artifacts and the development agents. Delivery is
# project-specific and opt-in: pass a target as the third argument only if you
# want it, and expect to edit what it writes.
TARGET="${1:?usage: bootstrap.sh [--dry-run] [--update-hooks] /path/to/repo [domain] [vercel|docker-vps]}"
DOMAIN="${2:-general}"
DELIVERY="${3:-}"

[ -d "$TARGET" ] || { echo "no such directory: $TARGET" >&2; exit 1; }

# The validators, the spec-validate hook and most commands run `python3`. On
# Windows the Microsoft Store alias answers to that name without being Python, so
# check it really runs before writing anything, rather than stop halfway.
if ! python3 -c 'import sys; sys.exit(sys.version_info < (3, 9))' >/dev/null 2>&1; then
  echo "python3 is missing, older than 3.9, or not really Python (on Windows, often" >&2
  echo "the Microsoft Store alias). See GETTING-STARTED.md, step 0, then re-run." >&2
  exit 1
fi

cd "$TARGET"

MERGE=(python3 "$SRC/scripts/settings_merge.py" "$SRC/assets/settings.hook.json" .claude/settings.json
       ${UPDATE_HOOKS[@]+"${UPDATE_HOOKS[@]}"})

# A settings file that cannot be merged (not valid JSON, the wrong shape) stops
# the install here, before anything is written, not halfway through.
if ! merge_check="$("${MERGE[@]}" --check 2>&1)"; then
  printf '%s\n' "$merge_check" >&2
  echo "bootstrap.sh: .claude/settings.json cannot be merged; nothing was installed." >&2
  exit 1
fi

say()  { printf '  %s\n' "$*"; }
# Every write goes through mkd, copy or a DRY_RUN test, so --dry-run can report
# it instead of doing it.
mkd()  { [ "$DRY_RUN" = 1 ] || mkdir -p "$@"; }
copy() {
  local from="$1" to="$2"
  if [ -e "$to" ]; then say "skip (exists)  $to"; return; fi
  if [ "$DRY_RUN" = 1 ]; then say "would write   $to"; return; fi
  mkdir -p "$(dirname "$to")"
  cp "$from" "$to"; say "wrote         $to"
}

if [ "$DRY_RUN" = 1 ]; then
  echo "Dry run: what installing dev-flow into $TARGET would do (default domain: $DOMAIN). Nothing is written."
else
  echo "Installing dev-flow into $TARGET (default domain: $DOMAIN)"
fi

# 1. The skill itself.
mkd .claude/skills/dev-flow
for f in SKILL.md README.md GETTING-STARTED.md; do copy "$SRC/$f" ".claude/skills/dev-flow/$f"; done
for d in scripts references assets; do
  mkd ".claude/skills/dev-flow/$d"
  for f in "$SRC/$d"/*; do [ -f "$f" ] || continue; copy "$f" ".claude/skills/dev-flow/$d/$(basename "$f")"; done
done
[ "$DRY_RUN" = 1 ] || chmod +x .claude/skills/dev-flow/scripts/*.py .claude/skills/dev-flow/scripts/*.sh

# 2. Where specs live.
mkd specs docs/adr
if [ -e specs/README.md ]; then
  :
elif [ "$DRY_RUN" = 1 ]; then
  say "would write   specs/README.md"
else
  cat > specs/README.md <<'EOF'
# Specs

One directory per issue: `specs/<issue-number>-<kebab-slug>/`.

- `prd.md` — generated by the dev-flow skill, validated in CI
- `plan.md`, `acceptance.md` — later stages, not yet automated

Requirement IDs (`REQ-001`...) are permanent. Plan tasks, acceptance cases, and
PR descriptions reference them. Never renumber; mark withdrawn requirements
`[WITHDRAWN]` in place.
EOF
fi
[ "$DRY_RUN" = 1 ] || say "ready         specs/, docs/adr/"

# 3. Issue template carrying the minimum payload.
copy "$SRC/assets/github-issue-template.md" ".github/ISSUE_TEMPLATE/spec-request.md"

# 4. CI gate.
copy "$SRC/assets/validate-prd.yml" ".github/workflows/validate-prd.yml"
copy "$SRC/assets/spec-pipeline.yml" ".github/workflows/spec-pipeline.yml"
copy "$SRC/assets/prototype-guard.yml" ".github/workflows/prototype-guard.yml"

# 5. Slash commands.
mkd .claude/commands
for f in "$SRC/commands"/*.md; do copy "$f" ".claude/commands/$(basename "$f")"; done

# 6. Hooks, and the project settings that wire them. settings_merge.py merges
# assets/settings.hook.json into .claude/settings.json, whether or not it exists:
# the three hooks, the tier-1 deny rules and the subagent depth (DR1), and
# autoMemoryEnabled: false (DR2). It prints each change.
for f in "$SRC/hooks"/*.sh; do copy "$f" ".claude/hooks/$(basename "$f")"; done
[ "$DRY_RUN" = 1 ] || chmod +x .claude/hooks/*.sh 2>/dev/null || true

if [ "$DRY_RUN" = 1 ]; then "${MERGE[@]}" --dry-run; else "${MERGE[@]}"; fi

# 7. Project config. This is the file that makes the delivery half
# language-agnostic: every command it runs is read from here.
if [ -e flow.json ]; then
  say "skip (exists)  flow.json"
elif [ "$DRY_RUN" = 1 ]; then
  say "would write   flow.json (domain: $DOMAIN, delivery: ${DELIVERY:-none})"
else
  case "$DELIVERY" in
    vercel)     cp "$SRC/optional-delivery/assets/flow.vercel.json" flow.json ;;
    docker-vps) cp "$SRC/optional-delivery/assets/flow.docker-vps.json" flow.json ;;
    *)          cp "$SRC/assets/flow.example.json" flow.json ;;
  esac
  python3 - "$DOMAIN" <<'PYEOF'
import json, sys, pathlib
p = pathlib.Path("flow.json"); c = json.loads(p.read_text())
c["domain"] = sys.argv[1]
p.write_text(json.dumps(c, indent=2) + "\n")
PYEOF
  say "wrote         flow.json (domain: $DOMAIN, delivery: ${DELIVERY:-none})"
  say "ACTION        fill in the commands in flow.json — the agents read them"
fi

# Whether the tests /harness generates are hidden from /implement: flow.json's
# acceptance_tests glob (build item 30, DECISIONS.md B15). Reported, never set:
# where the tests go is the project's choice (GETTING-STARTED.md, step 3b).
if [ -e flow.json ]; then
  tests_rc=0
  tests_glob="$(python3 "$SRC/scripts/pipeline_config.py" --get acceptance_tests 2>&1)" || tests_rc=$?
  if [ "$tests_rc" = 0 ]; then
    say "hidden        the generated acceptance tests: $tests_glob (flow.json acceptance_tests)"
  elif [ "$tests_rc" = 4 ]; then
    say "NOTE          flow.json sets no acceptance_tests, so nothing hides the tests /harness"
    say "              generates from /implement. Set it (GETTING-STARTED.md, step 3b)"
  else
    say "WARNING       flow.json: $tests_glob"
  fi
else
  say "NOTE          the flow.json it would write sets no acceptance_tests, so nothing would hide"
  say "              the tests /harness generates from /implement (GETTING-STARTED.md, step 3b)"
fi

if [ "$DRY_RUN" = 1 ]; then
  say "would write   .claude/skills/dev-flow/DEFAULT_DOMAIN ($DOMAIN)"
else
  echo "$DOMAIN" > .claude/skills/dev-flow/DEFAULT_DOMAIN
fi

# 8. .gitignore: Playwright Test's output directories, for projects that use it
# as their acceptance command (GETTING-STARTED.md, step 3b), .dev-flow-run/,
# where /implement and /verify keep the markers the guard hooks read and the spec
# job keeps the issue it fetched, and __pycache__/, the bytecode Python writes
# beside the validators (.claude/skills/dev-flow/scripts/__pycache__/). Not
# ignored, it changes the tree evidence.py fingerprints, and every record is
# STALE (M1). Appended only when absent; an entry counts as present in any of the
# spellings that ignore the directory at the root (name, name/, /name, /name/),
# and __pycache__/ only in those that ignore it at any depth (name, name/,
# **/name, **/name/). Existing lines are never changed, and the file's own line
# endings are kept.
GITIGNORE_ENTRIES=(playwright-report/ test-results/ .dev-flow-run/ __pycache__/)
missing=()
for e in "${GITIGNORE_ENTRIES[@]}"; do
  n="${e%/}"; n="${n//./[.]}"  # a literal dot in the pattern below
  case "$e" in
    __pycache__/) lead='(\*\*/)?' ;;
    *)            lead='/?' ;;
  esac
  if [ -f .gitignore ] && grep -qxE "[[:space:]]*${lead}${n}/?[[:space:]]*" .gitignore; then continue; fi
  missing+=("$e")
done
if [ "${#missing[@]}" = 0 ]; then
  say "skip (present) .gitignore (${GITIGNORE_ENTRIES[*]})"
elif [ "$DRY_RUN" = 1 ]; then
  if [ -e .gitignore ]; then verb="would append "; else verb="would write  "; fi
  say "$verb .gitignore (${missing[*]})"
else
  verb="wrote        "
  eol=$'\n'
  if [ -e .gitignore ]; then
    verb="appended     "
    # Not `grep $'\r$'`: under Git Bash it did not match a CRLF file (observed).
    if [ -n "$(tr -cd '\r' < .gitignore)" ]; then eol=$'\r\n'; fi
    # A last line with no newline would otherwise run into the comment line.
    if [ -s .gitignore ] && [ -n "$(tail -c 1 .gitignore)" ]; then printf '%s' "$eol" >> .gitignore; fi
  fi
  { printf '# dev-flow bootstrap: Playwright Test output, dev-flow run state, Python bytecode%s' "$eol"
    for e in "${missing[@]}"; do printf '%s%s' "$e" "$eol"; done; } >> .gitignore
  say "$verb .gitignore (${missing[*]})"
fi

# 9. Optional delivery layer. Opt-in, because how a project releases and deploys
# does not generalise — treat what this installs as a starting point to edit, not
# a finished pipeline.
if [ -n "$DELIVERY" ]; then
  for f in "$SRC/optional-delivery/commands"/*.md; do
    copy "$f" ".claude/commands/$(basename "$f")"
  done
  copy "$SRC/optional-delivery/scripts/validate_delivery.py" \
       ".claude/skills/dev-flow/scripts/validate_delivery.py"
  copy "$SRC/optional-delivery/assets/delivery-template.md" \
       ".claude/skills/dev-flow/assets/delivery-template.md"
  copy "$SRC/optional-delivery/assets/deliver.yml" ".github/workflows/deliver.yml"
  [ "$DRY_RUN" = 1 ] || say "wrote         delivery layer ($DELIVERY) — review deliver.yml before enabling it"
fi

if [ "$DRY_RUN" = 1 ]; then
  echo
  echo "Dry run finished: nothing was written. Run again without --dry-run to install."
  exit 0
fi

echo
echo "Done. Full flow in Claude Code:"
echo "  /spec-setup $DOMAIN    finish setup (installs the mattpocock skills)"
echo "  /grill-me              sharpen the idea, then open an issue"
echo "  /prototype             build a throwaway probe when talking cannot settle it"
echo "  /verdict 14            fold the prototype result into the spec as evidence"
echo "  /spec 14               issue      -> prd.md      (or label it spec:auto)"
echo "  /plan 14               prd.md     -> plan.md     [you approve here]"
echo "  /acceptance 14         prd.md     -> acceptance.md (forked context)"
echo "  /implement 14          plan.md    -> code        (acceptance.md blocked)"
echo "  /harness 14            acceptance.md -> runnable tests (forked context)"
echo "  /verify 14             acceptance.md vs code, failures routed by cause"
echo "  /review 14             pre-merge: lint, tests, traceability, craft"
echo "  /spec-check            validate every artifact"
echo "  /coverage              requirement coverage matrix"
